modLoader = "javafml"
loaderVersion = "[40,)"
license = "MIT"

[[mods]]
    modId = "metallurgy"
    version = "${file.jarVersion}"
    displayName = "Metallurgy"
    logoFile = "metallurgy.png"
    credits = "Seleclipse, Baka-Gourd, GBLodb"
    authors = "Seleclipse, Baka-Gourd, GBLodb, Draming"
    description='''A Minecraft 1.18.2 mod about restoring the metallurgical process in reality.'''

[[dependencies.metallurgy]]
    modId = "forge"
    mandatory=true
    versionRange = "[40,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.metallurgy]]
    modId = "minecraft"
    mandatory=true
    versionRange = "[1.18.2,1.19)"
    ordering = "NONE"
    side = "BOTH"
